# Generated by Django 5.0.6 on 2024-05-21 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watchlist",
        ),
    ]
