# Generated by Django 5.0.6 on 2024-05-26 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_listing_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="starting_bid",
            new_name="sbid",
        ),
    ]
